<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Provinsi;
use App\Models\Kota;

class ProvincesCitiesSeeder extends Seeder
{
    public function run()
    {
        $provinces = [
            'Aceh' => [
                ['nama' => 'Kabupaten Aceh Barat'],
                ['nama' => 'Kabupaten Aceh Barat Daya'],
                ['nama' => 'Kabupaten Aceh Besar'],
                ['nama' => 'Kabupaten Aceh Jaya'],
                ['nama' => 'Kabupaten Aceh Selatan'],
                ['nama' => 'Kabupaten Aceh Singkil'],
                ['nama' => 'Kabupaten Aceh Tamiang'],
                ['nama' => 'Kabupaten Aceh Tengah'],
                ['nama' => 'Kabupaten Aceh Tenggara'],
                ['nama' => 'Kabupaten Aceh Timur'],
                ['nama' => 'Kabupaten Aceh Utara'],
                ['nama' => 'Kabupaten Benar Meriah'],
                ['nama' => 'Kabupaten Bireuen'],
                ['nama' => 'Kabupaten Gayo Lues'],
                ['nama' => 'Kabupaten Nagan Raya'],
                ['nama' => 'Kabupaten Pidie'],
                ['nama' => 'Kabupaten Pidie Jaya'],
                ['nama' => 'Kabupaten Simeulue'],
                ['nama' => 'Kota Banda Aceh'],
                ['nama' => 'Kota Langsa'],
                ['nama' => 'Kota Lhokseumawe'],
                ['nama' => 'Kota Sabang'],
                ['nama' => 'Kota Subulussalam'],
            ],
            'Sumatera Utara' => [
                ['nama' => 'Kabupaten Asahan'],
                ['nama' => 'Kabupaten Batu Bara'],
                ['nama' => 'Kabupaten Dairi'],
                ['nama' => 'Kabupaten Deli Serdang'],
                ['nama' => 'Kabupaten Humbang Hasundutan'],
                ['nama' => 'Kabupaten Karo'],
                ['nama' => 'Kabupaten Labuhanbatu'],
                ['nama' => 'Kabupaten Labuhanbatu Selatan'],
                ['nama' => 'Kabupaten Labuhanbatu Utara'],
                ['nama' => 'Kabupaten Langkat'],
                ['nama' => 'Kabupaten Mandailing Natal'],
                ['nama' => 'Kabupaten Nias'],
                ['nama' => 'Kabupaten Nias Barat'],
                ['nama' => 'Kabupaten Nias Selatan'],
                ['nama' => 'Kabupaten Nias Utara'],
                ['nama' => 'Kabupaten Padang Lawas'],
                ['nama' => 'Kabupaten Padang Lawas Utara'],
                ['nama' => 'Kabupaten Pakpak Barat'],
                ['nama' => 'Kabupaten Samosir'],
                ['nama' => 'Kabupaten Serdang Bedagai'],
                ['nama' => 'Kabupaten Simalungun'],
                ['nama' => 'Kabupaten Tapanuli Selatan'],
                ['nama' => 'Kabupaten Tapanuli Utara'],
                ['nama' => 'Kabupaten Toba'],
                ['nama' => 'Kota Binjai'],
                ['nama' => 'Kota Gunungsitoli'],
                ['nama' => 'Kota Medan'],
                ['nama' => 'Kota Padangsidimpuan'],
                ['nama' => 'Kota Pematangsiantar'],
                ['nama' => 'Kota Sibolga'],
                ['nama' => 'Kota Tanjungbalai'],
                ['nama' => 'Kota Tebing Tinggi'],
            ],
            'Sumatera Barat' => [
                ['nama' => 'Kabupaten Agam'],
                ['nama' => 'Kabupaten Dharmasraya'],
                ['nama' => 'Kabupaten Kepulauan Mentawai'],
                ['nama' => 'Kabupaten Lima Puluh Kota'],
                ['nama' => 'Kabupaten Padang Pariaman'],
                ['nama' => 'Kabupaten Pasaman'],
                ['nama' => 'Kabupaten Pasaman Barat'],
                ['nama' => 'Kabupaten Sijunjung'],
                ['nama' => 'Kabupaten Solok'],
                ['nama' => 'Kabupaten Solok Selatan'],
                ['nama' => 'Kabupaten Tanah Datar'],
                ['nama' => 'Kota Bukittinggi'],
                ['nama' => 'Kota Padang'],
                ['nama' => 'Kota Padang Panjang'],
                ['nama' => 'Kota Pariaman'],
                ['nama' => 'Kota Payakumbuh'],
                ['nama' => 'Kota Sawahlunto'],
                ['nama' => 'Kota Solok'],
                ['nama' => 'Kabupaten Pesisir Selatan'],
            ],
            'Riau' => [
                ['nama' => 'Kabupaten Bengkalis'],
                ['nama' => 'Kabupaten Indragiri Hilir'],
                ['nama' => 'Kabupaten Indragiri Hulu'],
                ['nama' => 'Kabupaten Kampar'],
                ['nama' => 'Kabupaten Kepulauan Meranti'],
                ['nama' => 'Kabupaten Kuantan Singingi'],
                ['nama' => 'Kabupaten Pelalawan'],
                ['nama' => 'Kabupaten Rokan Hilir'],
                ['nama' => 'Kabupaten Rokan Hulu'],
                ['nama' => 'Kabupaten Siak'],
                ['nama' => 'Kota Dumai'],
                ['nama' => 'Kota Pekanbaru'],
            ],
            'Jambi' => [
                ['nama' => 'Kabupaten Batanghari'],
                ['nama' => 'Kabupaten Bungo'],
                ['nama' => 'Kabupaten Kerinci'],
                ['nama' => 'Kabupaten Merangin'],
                ['nama' => 'Kabupaten Muaro Jambi'],
                ['nama' => 'Kabupaten Sarolangun'],
                ['nama' => 'Kabupaten Tanjung Jabung Barat'],
                ['nama' => 'Kabupaten Tanjung Jabung Timur'],
                ['nama' => 'Kabupaten Tebo'],
                ['nama' => 'Kota Jambi'],
                ['nama' => 'Kota Sungai Penuh'],
            ],
            'Sumatera Selatan' => [
                ['nama' => 'Kabupaten Banyuasin'],
                ['nama' => 'Kabupaten Empat Lawang'],
                ['nama' => 'Kabupaten Lahat'],
                ['nama' => 'Kabupaten Muara Enim'],
                ['nama' => 'Kabupaten Musi Banyuasin'],
                ['nama' => 'Kabupaten Musi Rawas'],
                ['nama' => 'Kabupaten Musi Rawas Utara'],
                ['nama' => 'Kabupaten Ogan Ilir'],
                ['nama' => 'Kabupaten Ogan Komering Ilir'],
                ['nama' => 'Kabupaten Ogan Komering Ulu'],
                ['nama' => 'Kabupaten Ogan Komering Ulu Selatan'],
                ['nama' => 'Kabupaten Ogan Komering Ulu Timur'],
                ['nama' => 'Kabupaten Penukal Abab Lematang Ilir'],
                ['nama' => 'Kota Lubuk Linggau'],
                ['nama' => 'Kota Pagar Alam'],
                ['nama' => 'Kota Palembang'],
                ['nama' => 'Kota Prabumulih'],
            ],
            'Bengkulu' => [
                ['nama' => 'Kabupaten Bengkulu Selatan'],
                ['nama' => 'Kabupaten Bengkulu Tengah'],
                ['nama' => 'Kabupaten Bengkulu Utara'],
                ['nama' => 'Kabupaten Kaur'],
                ['nama' => 'Kabupaten Kepahiang'],
                ['nama' => 'Kabupaten Lebong'],
                ['nama' => 'Kabupaten Mukomuko'],
                ['nama' => 'Kabupaten Rejang Lebong'],
                ['nama' => 'Kabupaten Seluma'],
                ['nama' => 'Kota Bengkulu'],
            ],
            'Lampung' => [
                ['nama' => 'Kota Bandar Lampung'],
                ['nama' => 'Kota Metro'],
                ['nama' => 'Kabupaten Lampung Selatan'],
                ['nama' => 'Kabupaten Lampung Utara'],
                ['nama' => 'Kabupaten Lampung Barat'],
                ['nama' => 'Kabupaten Lampung Tengah'],
                ['nama' => 'Kabupaten Lampung Timur'],
                ['nama' => 'Kabupaten Way Kanan'],
                ['nama' => 'Kabupaten Tulang Bawang'],
                ['nama' => 'Kabupaten Mesuji'],
                ['nama' => 'Kabupaten Pesawaran'],
                ['nama' => 'Kabupaten Pesisir Barat'],
                ['nama' => 'Kabupaten Pringsewu'],
                ['nama' => 'Kabupaten Tanggamus'],
                ['nama' => 'Kabupaten Tulang Bawang Barat'],
            ],
            'Bangka Belitung' => [
                ['nama' => 'Kabupaten Bangka'],
                ['nama' => 'Kabupaten Bangka Barat'],
                ['nama' => 'Kabupaten Bangka Selatan'],
                ['nama' => 'Kabupaten Bangka Tengah'],
                ['nama' => 'Kabupaten Belitung'],
                ['nama' => 'Kabupaten Belitung Timur'],
                ['nama' => 'Kota Pangkal Pinang'],
            ],
            'Kepulauan Riau' => [
                ['nama' => 'Kabupaten Bintan'],
                ['nama' => 'Kabupaten Karimun'],
                ['nama' => 'Kabupaten Kepulauan Anambas'],
                ['nama' => 'Kabupaten Lingga'],
                ['nama' => 'Kabupaten Natuna'],
                ['nama' => 'Kota Batam'],
                ['nama' => 'Kota Tanjung Pinang'],
            ],
            'Daerah Khusus Ibukota Jakarta' => [
                ['nama' => 'Kabupaten Administrasi Kepulauan Seribu'],
                ['nama' => 'Kota Administrasi Jakarta Barat'],
                ['nama' => 'Kota Administrasi Jakarta Pusat'],
                ['nama' => 'Kota Administrasi Jakarta Selatan'],
                ['nama' => 'Kota Administrasi Jakarta Timur'],
                ['nama' => 'Kota Administrasi Jakarta Utara'],
            ],
            'Jawa Barat' => [
                ['nama' => 'Kabupaten Bandung'],
                ['nama' => 'Kabupaten Bandung Barat'],
                ['nama' => 'Kabupaten Bekasi'],
                ['nama' => 'Kabupaten Bogor'],
                ['nama' => 'Kabupaten Ciamis'],
                ['nama' => 'Kabupaten Cianjur'],
                ['nama' => 'Kabupaten Cirebon'],
                ['nama' => 'Kabupaten Garut'],
                ['nama' => 'Kabupaten Indramayu'],
                ['nama' => 'Kabupaten Karawang'],
                ['nama' => 'Kabupaten Kuningan'],
                ['nama' => 'Kabupaten Majalengka'],
                ['nama' => 'Kabupaten Pangandaran'],
                ['nama' => 'Kabupaten Purwakarta'],
                ['nama' => 'Kabupaten Subang'],
                ['nama' => 'Kabupaten Sukabumi'],
                ['nama' => 'Kabupaten Sumedang'],
                ['nama' => 'Kabupaten Tasikmalaya'],
                ['nama' => 'Kota Bandung'],
                ['nama' => 'Kota Bekasi'],
                ['nama' => 'Kota Bogor'],
                ['nama' => 'Kota Cimahi'],
                ['nama' => 'Kota Cirebon'],
                ['nama' => 'Kota Depok'],
                ['nama' => 'Kota Sukabumi'],
                ['nama' => 'Kota Tasikmalaya'],
            ],
            'Jawa Tengah' => [
                ['nama' => 'Kabupaten Banjarnegara'],
                ['nama' => 'Kabupaten Banyumas'],
                ['nama' => 'Kabupaten Batang'],
                ['nama' => 'Kabupaten Blora'],
                ['nama' => 'Kabupaten Boyolali'],
                ['nama' => 'Kabupaten Brebes'],
                ['nama' => 'Kabupaten Cilacap'],
                ['nama' => 'Kabupaten Demak'],
                ['nama' => 'Kabupaten Grobogan'],
                ['nama' => 'Kabupaten Jepara'],
                ['nama' => 'Kabupaten Karanganyar'],
                ['nama' => 'Kabupaten Kebumen'],
                ['nama' => 'Kabupaten Kendal'],
                ['nama' => 'Kabupaten Klaten'],
                ['nama' => 'Kabupaten Kudus'],
                ['nama' => 'Kabupaten Magelang'],
                ['nama' => 'Kabupaten Pati'],
                ['nama' => 'Kabupaten Pekalongan'],
                ['nama' => 'Kabupaten Pemalang'],
                ['nama' => 'Kabupaten Purbalingga'],
                ['nama' => 'Kabupaten Purworejo'],
                ['nama' => 'Kabupaten Rembang'],
                ['nama' => 'Kabupaten Semarang'],
                ['nama' => 'Kabupaten Sragen'],
                ['nama' => 'Kabupaten Sukoharjo'],
                ['nama' => 'Kabupaten Tegal'],
                ['nama' => 'Kabupaten Temanggung'],
                ['nama' => 'Kabupaten Wonogiri'],
                ['nama' => 'Kabupaten Wonosobo'],
                ['nama' => 'Kota Magelang'],
                ['nama' => 'Kota Pekalongan'],
                ['nama' => 'Kota Salatiga'],
                ['nama' => 'Kota Semarang'],
                ['nama' => 'Kota Surakarta'],
                ['nama' => 'Kota Tegal'],
            ],
            'Daerah Istimewa Yogyakarta' => [
                ['nama' => 'Kabupaten Bantul'],
                ['nama' => 'Kabupaten Gunungkidul'],
                ['nama' => 'Kabupaten Kulon Progo'],
                ['nama' => 'Kabupaten Sleman'],
                ['nama' => 'Kota Yogyakarta'],
            ],
            'Jawa Timur' => [
                ['nama' => 'Kabupaten Bangkalan'],
                ['nama' => 'Kabupaten Banyuwangi'],
                ['nama' => 'Kabupaten Blitar'],
                ['nama' => 'Kabupaten Bojonegoro'],
                ['nama' => 'Kabupaten Bondowoso'],
                ['nama' => 'Kabupaten Gresik'],
                ['nama' => 'Kabupaten Jember'],
                ['nama' => 'Kabupaten Jombang'],
                ['nama' => 'Kabupaten Kediri'],
                ['nama' => 'Kabupaten Lamongan'],
                ['nama' => 'Kabupaten Lumajang'],
                ['nama' => 'Kabupaten Madiun'],
                ['nama' => 'Kabupaten Magetan'],
                ['nama' => 'Kabupaten Malang'],
                ['nama' => 'Kabupaten Mojokerto'],
                ['nama' => 'Kabupaten Nganjuk'],
                ['nama' => 'Kabupaten Ngawi'],
                ['nama' => 'Kabupaten Pacitan'],
                ['nama' => 'Kabupaten Pamekasan'],
                ['nama' => 'Kabupaten Pasuruan'],
                ['nama' => 'Kabupaten Ponorogo'],
                ['nama' => 'Kabupaten Probolinggo'],
                ['nama' => 'Kabupaten Sampang'],
                ['nama' => 'Kabupaten Sidoarjo'],
                ['nama' => 'Kabupaten Situbondo'],
                ['nama' => 'Kabupaten Sumenep'],
                ['nama' => 'Kabupaten Trenggalek'],
                ['nama' => 'Kabupaten Tuban'],
                ['nama' => 'Kabupaten Tulungagung'],
                ['nama' => 'Kota Batu'],
                ['nama' => 'Kota Blitar'],
                ['nama' => 'Kota Kediri'],
                ['nama' => 'Kota Madiun'],
                ['nama' => 'Kota Malang'],
                ['nama' => 'Kota Mojokerto'],
                ['nama' => 'Kota Pasuruan'],
                ['nama' => 'Kota Probolinggo'],
                ['nama' => 'Kota Surabaya'],
            ],
            'Banten' => [
                ['nama' => 'Kabupaten Lebak'],
                ['nama' => 'Kabupaten Pandeglang'],
                ['nama' => 'Kabupaten Serang'],
                ['nama' => 'Kabupaten Tangerang'],
                ['nama' => 'Kota Cilegon'],
                ['nama' => 'Kota Serang'],
                ['nama' => 'Kota Tangerang'],
                ['nama' => 'Kota Tangerang Selatan'],
            ],
            'Bali' => [
                ['nama' => 'Kabupaten Badung'],
                ['nama' => 'Kabupaten Bangli'],
                ['nama' => 'Kabupaten Buleleng'],
                ['nama' => 'Kabupaten Gianyar'],
                ['nama' => 'Kabupaten Jembrana'],
                ['nama' => 'Kabupaten Karangasem'],
                ['nama' => 'Kabupaten Klungkung'],
                ['nama' => 'Kabupaten Tabanan'],
                ['nama' => 'Kota Denpasar'],
            ],
            'Nusa Tenggara Barat' => [
                ['nama' => 'Kabupaten Bima'],
                ['nama' => 'Kabupaten Dompu'],
                ['nama' => 'Kabupaten Lombok Barat'],
                ['nama' => 'Kabupaten Lombok Tengah'],
                ['nama' => 'Kabupaten Lombok Timur'],
                ['nama' => 'Kabupaten Lombok Utara'],
                ['nama' => 'Kabupaten Sumbawa'],
                ['nama' => 'Kabupaten Sumbawa Barat'],
                ['nama' => 'Kota Bima'],
                ['nama' => 'Kota Mataram'],
            ],
            'Nusa Tenggara Timur' => [
                ['nama' => 'Kabupaten Alor'],
                ['nama' => 'Kabupaten Belu'],
                ['nama' => 'Kabupaten Ende'],
                ['nama' => 'Kabupaten Flores Timur'],
                ['nama' => 'Kabupaten Kupang'],
                ['nama' => 'Kabupaten Lembata'],
                ['nama' => 'Kabupaten Malaka'],
                ['nama' => 'Kabupaten Manggarai'],
                ['nama' => 'Kabupaten Manggarai Barat'],
                ['nama' => 'Kabupaten Manggarai Timur'],
                ['nama' => 'Kabupaten Nagekeo'],
                ['nama' => 'Kabupaten Ngada'],
                ['nama' => 'Kabupaten Rote Ndao'],
                ['nama' => 'Kabupaten Sabu Raijua'],
                ['nama' => 'Kabupaten Sikka'],
                ['nama' => 'Kabupaten Sumba Barat'],
                ['nama' => 'Kabupaten Sumba Barat Daya'],
                ['nama' => 'Kabupaten Sumba Tengah'],
                ['nama' => 'Kabupaten Sumba Timur'],
                ['nama' => 'Kabupaten Timor Tengah Selatan'],
                ['nama' => 'Kabupaten Timor Tengah Utara'],
                ['nama' => 'Kota Kupang'],
            ],
            'Kalimantan Barat' => [
                ['nama' => 'Kabupaten Bengkayang'],
                ['nama' => 'Kabupaten Kapuas Hulu'],
                ['nama' => 'Kabupaten Kayong Utara'],
                ['nama' => 'Kabupaten Ketapang'],
                ['nama' => 'Kabupaten Kubu Raya'],
                ['nama' => 'Kabupaten Landak'],
                ['nama' => 'Kabupaten Melawi'],
                ['nama' => 'Kabupaten Mempawah'],
                ['nama' => 'Kabupaten Sambas'],
                ['nama' => 'Kabupaten Sanggau'],
                ['nama' => 'Kabupaten Sekadau'],
                ['nama' => 'Kabupaten Sintang'],
                ['nama' => 'Kota Pontianak'],
                ['nama' => 'Kota Singkawang'],
            ],
            'Kalimantan Tengah' => [
                ['nama' => 'Kabupaten Barito Selatan'],
                ['nama' => 'Kabupaten Barito Timur'],
                ['nama' => 'Kabupaten Barito Utara'],
                ['nama' => 'Kabupaten Gunung Mas'],
                ['nama' => 'Kabupaten Kapuas'],
                ['nama' => 'Kabupaten Katingan'],
                ['nama' => 'Kabupaten Kotawaringin Barat'],
                ['nama' => 'Kabupaten Kotawaringin Timur'],
                ['nama' => 'Kabupaten Lamandau'],
                ['nama' => 'Kabupaten Murung Raya'],
                ['nama' => 'Kabupaten Pulang Pisau'],
                ['nama' => 'Kabupaten Sukamara'],
                ['nama' => 'Kabupaten Seruyan'],
                ['nama' => 'Kota Palangkaraya'],
            ],
            'Kalimantan Selatan' => [
                ['nama' => 'Kabupaten Balangan'],
                ['nama' => 'Kabupaten Banjar'],
                ['nama' => 'Kabupaten Barito Kuala'],
                ['nama' => 'Kabupaten Hulu Sungai Selatan'],
                ['nama' => 'Kabupaten Hulu Sungai Tengah'],
                ['nama' => 'Kabupaten Hulu Sungai Utara'],
                ['nama' => 'Kabupaten Kotabaru'],
                ['nama' => 'Kabupaten Tabalong'],
                ['nama' => 'Kabupaten Tanah Bambu'],
                ['nama' => 'Kabupaten Tanah Laut'],
                ['nama' => 'Kabupaten Tapin'],
                ['nama' => 'Kota Banjarbaru'],
                ['nama' => 'Kota Banjarmasin'],
            ],
            'Kalimantan Timur' => [
                ['nama' => 'Kabupaten Berau'],
                ['nama' => 'Kabupaten Kutai Barat'],
                ['nama' => 'Kabupaten Kutai Kartanegara'],
                ['nama' => 'Kabupaten Kutai Timur'],
                ['nama' => 'Kabupaten Mahakam Ulu'],
                ['nama' => 'Kabupaten Paser'],
                ['nama' => 'Kabupaten Penajam Paser Utara'],
                ['nama' => 'Kota Balikpapan'],
                ['nama' => 'Kota Bontang'],
                ['nama' => 'Kota Samarinda'],
            ],
            'Kalimantan Utara' => [
                ['nama' => 'Kabupaten Bulungan'],
                ['nama' => 'Kabupaten Malinau'],
                ['nama' => 'Kabupaten Nunukan'],
                ['nama' => 'Kabupaten Tana Tidung'],
                ['nama' => 'Kota Tarakan'],
            ],
            'Sulawesi Utara' => [
                ['nama' => 'Kabupaten Bolaang Mongondow'],
                ['nama' => 'Kabupaten Bolaang Mongondow Selatan'],
                ['nama' => 'Kabupaten Bolaang Mongondow Timur'],
                ['nama' => 'Kabupaten Bolaang Mongondow Utara'],
                ['nama' => 'Kabupaten Kepulauan Sangihe'],
                ['nama' => 'Kabupaten Kepulauan Siau Tagulandang Biaro'],
                ['nama' => 'Kabupaten Kepulauan Talaud'],
                ['nama' => 'Kabupaten Minahasa'],
                ['nama' => 'Kabupaten Minahasa Selatan'],
                ['nama' => 'Kabupaten Minahasa Tenggara'],
                ['nama' => 'Kabupaten Minahasa Utara'],
                ['nama' => 'Kota Bitung'],
                ['nama' => 'Kota Kotamobagu'],
                ['nama' => 'Kota Manado'],
                ['nama' => 'Kota Tomohon'],
            ],
            'Sulawesi Tengah' => [
                ['nama' => 'Kabupaten Banggai'],
                ['nama' => 'Kabupaten Banggai Kepulauan'],
                ['nama' => 'Kabupaten Banggai Laut'],
                ['nama' => 'Kabupaten Buol'],
                ['nama' => 'Kabupaten Donggala'],
                ['nama' => 'Kabupaten Morowali'],
                ['nama' => 'Kabupaten Morowali Utara'],
                ['nama' => 'Kabupaten Parigi Moutong'],
                ['nama' => 'Kabupaten Poso'],
                ['nama' => 'Kabupaten Sigi'],
                ['nama' => 'Kabupaten Tojo Una-Una'],
                ['nama' => 'Kabupaten Tolitoli'],
                ['nama' => 'Kota Palu'],
            ],
            'Sulawesi Selatan' => [
                ['nama' => 'Kabupaten Bantaeng'],
                ['nama' => 'Kabupaten Barru'],
                ['nama' => 'Kabupaten Bone'],
                ['nama' => 'Kabupaten Bulukumba'],
                ['nama' => 'Kabupaten Enrekang'],
                ['nama' => 'Kabupaten Gowa'],
                ['nama' => 'Kabupaten Jeneponto'],
                ['nama' => 'Kabupaten Kepulauan Selayar'],
                ['nama' => 'Kabupaten Luwu'],
                ['nama' => 'Kabupaten Luwu Timur'],
                ['nama' => 'Kabupaten Luwu Utara'],
                ['nama' => 'Kabupaten Maros'],
                ['nama' => 'Kabupaten Pangkajene Kepulauan'],
                ['nama' => 'Kabupaten Pinrang'],
                ['nama' => 'Kabupaten Sidenreng Rappang'],
                ['nama' => 'Kabupaten Sinjai'],
                ['nama' => 'Kabupaten Soppeng'],
                ['nama' => 'Kabupaten Takalar'],
                ['nama' => 'Kabupaten Tana Toraja'],
                ['nama' => 'Kabupaten Toraja Utara'],
                ['nama' => 'Kabupaten Wajo'],
                ['nama' => 'Kota Makassar'],
                ['nama' => 'Kota Palopo'],
                ['nama' => 'Kota Parepare'],
            ],
            'Sulawesi Tenggara' => [
                ['nama' => 'Kabupaten Bombana'],
                ['nama' => 'Kabupaten Buton'],
                ['nama' => 'Kabupaten Buton Selatan'],
                ['nama' => 'Kabupaten Buton Tengah'],
                ['nama' => 'Kabupaten Buton Utara'],
                ['nama' => 'Kabupaten Kolaka'],
                ['nama' => 'Kabupaten Kolaka Timur'],
                ['nama' => 'Kabupaten Kolaka Utara'],
                ['nama' => 'Kabupaten Konawe'],
                ['nama' => 'Kabupaten Konawe Kepulauan'],
                ['nama' => 'Kabupaten Konawe Selatan'],
                ['nama' => 'Kabupaten Konawe Utara'],
                ['nama' => 'Kabupaten Muna'],
                ['nama' => 'Kabupaten Muna Barat'],
                ['nama' => 'Kabupaten Wakatobi'],
                ['nama' => 'Kota Baubau'],
                ['nama' => 'Kota Kendari'],
            ],
            'Gorontalo' => [
                ['nama' => 'Kabupaten Boalemo'],
                ['nama' => 'Kabupaten Bone Bolango'],
                ['nama' => 'Kabupaten Gorontalo'],
                ['nama' => 'Kabupaten Gorontalo Utara'],
                ['nama' => 'Kabupaten Pohuwato'],
                ['nama' => 'Kota Gorontalo'],
            ],
            'Sulawesi Barat' => [
                ['nama' => 'Kabupaten Majene'],
                ['nama' => 'Kabupaten Mamasa'],
                ['nama' => 'Kabupaten Mamuju'],
                ['nama' => 'Kabupaten Mamuju Tengah'],
                ['nama' => 'Kabupaten Pasangkayu'],
                ['nama' => 'Kabupaten Polewali Mandar'],
            ],
            'Maluku' => [
                ['nama' => 'Kabupaten Buru'],
                ['nama' => 'Kabupaten Buru Selatan'],
                ['nama' => 'Kabupaten Kepulauan Aru'],
                ['nama' => 'Kabupaten Kepulauan Tanimbar'],
                ['nama' => 'Kabupaten Maluku Barat Daya'],
                ['nama' => 'Kabupaten Maluku Tengah'],
                ['nama' => 'Kabupaten Maluku Tenggara'],
                ['nama' => 'Kota Ambon'],
                ['nama' => 'Kabupaten Seram Bagian Barat'],
                ['nama' => 'Kabupaten Seram Bagian Timur'],
                ['nama' => 'Kota Tual'],
            ],
            'Maluku Utara' => [
                ['nama' => 'Kabupaten Halmahera Barat'],
                ['nama' => 'Kabupaten Halmahera Selatan'],
                ['nama' => 'Kabupaten Halmahera Tengah'],
                ['nama' => 'Kabupaten Halmahera Timur'],
                ['nama' => 'Kabupaten Halmahera Utara'],
                ['nama' => 'Kabupaten Kepulauan Sula'],
                ['nama' => 'Kabupaten Pulau Morotai'],
                ['nama' => 'Kabupaten Pulau Taliabu'],
                ['nama' => 'Kota Ternate'],
                ['nama' => 'Kota Tidore Kepulauan'],
            ],
            'Papua' => [
                ['nama' => 'Kabupaten Biak Numfor'],
                ['nama' => 'Kabupaten Jayapura'],
                ['nama' => 'Kabupaten Keerom'],
                ['nama' => 'Kabupaten Kepulauan Yapen'],
                ['nama' => 'Kabupaten Mamberamo Raya'],
                ['nama' => 'Kabupaten Sarmi'],
                ['nama' => 'Kabupaten Supiori'],
                ['nama' => 'Kabupaten Waropen'],
                ['nama' => 'Kota Jayapura'],
            ],
            'Papua Barat' => [
                ['nama' => 'Kabupaten Fakfak'],
                ['nama' => 'Kabupaten Kaimana'],
                ['nama' => 'Kabupaten Manokwari'],
                ['nama' => 'Kabupaten Manokwari Selatan'],
                ['nama' => 'Kabupaten Pegunungan Arfak'],
                ['nama' => 'Kabupaten Teluk Bintuni'],
                ['nama' => 'Kabupaten Teluk Wondama'],
            ],
            'Papua Selatan' => [
                ['nama' => 'Kabupaten Asmat'],
                ['nama' => 'Kabupaten Boven Digoel'],
                ['nama' => 'Kabupaten Mappi'],
                ['nama' => 'Kabupaten Merauke'],
            ],
            'Papua Tengah' => [
                ['nama' => 'Kabupaten Deiyai'],
                ['nama' => 'Kabupaten Dogiyai'],
                ['nama' => 'Kabupaten Intan Jaya'],
                ['nama' => 'Kabupaten Mimika'],
                ['nama' => 'Kabupaten Nabire'],
                ['nama' => 'Kabupaten Paniai'],
                ['nama' => 'Kabupaten Puncak'],
                ['nama' => 'Kabupaten Puncak Jaya'],
            ],
            'Papua Pegunungan' => [
                ['nama' => 'Kabupaten Jayawijaya'],
                ['nama' => 'Kabupaten Lanny Jaya'],
                ['nama' => 'Kabupaten Mamberamo Tengah'],
                ['nama' => 'Kabupaten Nduga'],
                ['nama' => 'Kabupaten Pegunungan Bintang'],
                ['nama' => 'Kabupaten Tolikara'],
                ['nama' => 'Kabupaten Yalimo'],
                ['nama' => 'Kabupaten Yahukimo'],
            ],
            'Papua Barat Daya' => [
                ['nama' => 'Kabupaten Maybrat'],
                ['nama' => 'Kabupaten Raja Ampat'],
                ['nama' => 'Kabupaten Sorong'],
                ['nama' => 'Kabupaten Sorong Selatan'],
                ['nama' => 'Kabupaten Tambrauw'],
                ['nama' => 'Kota Sorong'],
            ],
        ];

        foreach ($provinces as $provinceName => $cities) {
            // Create province
            $province = Provinsi::create([
                'nama' => $provinceName
            ]);

            // Create cities for this province
            foreach ($cities as $city) {
                Kota::create([
                    'provinsi_id' => $province->id,
                    'nama' => $city['nama'],
                    'kode_pos' => null
                ]);
            }
        }

        $this->command->info('Provinces and cities seeded successfully!');
    }
}
